### ISSUE TITLE
Dependency clean up

### ISSUE THREAD

**Issue by smil2k** [sidhant92/bool-parser-java#27]
Hi,

I looked at your code and I like it very much, I would like to use it in my project. 
My only concern at the moment is, that it brings many dependencies into my application which are not really needed.

1) vavr 
Only "Try" is used from this entire library. It seems the purpose of it to catch exceptions and present them along with the result. Throwing exceptions is a java thing, probably it is ok to just throw them, users will catch or use Try on them if they want.

2) logging
Slf4j is ok, it is the quasi standard, but adding logback on the classpath is already invasive as I could not use it in a container which provides slf4j eg. quarkus.
Also, I've checked the usages of the logger: I would not expect from a library to log things on error level. I think an exception is more appropriate.

eg. 
```
            log.error("Invalid left container type {} for operator {}", containerDataType, operator);
            throw new InvalidContainerTypeException();
```
I would expect the message in the exception itself. 

or

```
        if (!containerDataType.isValid(dataType, leftOperand)) {
            log.error("Validation failed for any operator for the operand {}", leftOperand);
            return false;
        }

...

       log.error("could not find key {} for the data {}", key, data);
        return Optional.empty();
``` 
Here I think an exception is probably better. Or if it is just a warning, then I would propagate it as a list back to the caller.

 3) Caffeine
Caching the expression is nice, but mandatory. At least from a classpath point of view. The BoolExpressionParser  has it as a field. Maybe adding a CachingBoolExpressionParser as a subclass would help a lot. (this way the caffeine dependency could be optional in the build.

4) Jackson
As I understood, jackson is used for checking data types. Jackson is a huge dependency and quite heavy.
Implementing these in a simple parseBoolean etc... operation would be much quicker and smaller.

If you like I can supply you with a simplified version of the library as a pull request. 

What do you think?

**Comment by sidhant92** [comment]
Thanks for the suggestions, will definitely pick up 3 immediately. Need some deeper thinking on other points. Will get back on those.

**Comment by sidhant92** [comment]
Won't remove 1 for now, because I prefer this way of exception handling, makes testing much easier and also on the consumer side code is more composable.

**Comment by sidhant92** [comment]
3 and 4 are done.

**Comment by smil2k** [comment]
Wow, you are quick :) 

Regarding 1:
I also like these type two of interfaces. Maybe optional would be something similar. (without the exception handling of course). My point is that Vavr is 1Mb. Alternatively there is another library which gears only on Try and Optional: https://mvnrepository.com/artifact/io.atlassian.fugue/fugue/ It is more focused, therefore only 100k.

**Comment by sidhant92** [comment]
Will explore this

**Comment by sidhant92** [comment]
All things resolved. Closing the issue.
